using System.Collections.Generic;
using Colossal;

namespace Agora.Mod.Core
{
    /// <summary>
    /// Supplies the display strings for the options page. Without a source registered, the settings
    /// UI falls back to raw locale ids like <c>Options.OPTION[Agora.Mod.Core.AgoraSettings.Enabled]</c>,
    /// which is the usual cause of a mod's options page looking broken.
    ///
    /// <para>
    /// English only (non-negotiable #10). The ids are generated by <see cref="AgoraSettings"/>'s
    /// inherited helpers rather than hand-written, so renaming a property cannot silently orphan
    /// its label.
    /// </para>
    /// </summary>
    public sealed class AgoraLocaleSource : IDictionarySource
    {
        private readonly AgoraSettings _settings;

        public AgoraLocaleSource(AgoraSettings settings)
        {
            _settings = settings;
        }

        public IEnumerable<KeyValuePair<string, string>> ReadEntries(
            IList<IDictionaryEntryError> errors,
            Dictionary<string, int> indexCounts)
        {
            return new Dictionary<string, string>
            {
                { _settings.GetSettingsLocaleID(), "Agora" },

                { _settings.GetOptionTabLocaleID(AgoraSettings.MainTab), "Main" },
                { _settings.GetOptionGroupLocaleID(AgoraSettings.GeneralGroup), "General" },
                { _settings.GetOptionGroupLocaleID(AgoraSettings.DiagnosticsGroup), "Diagnostics" },

                { _settings.GetOptionLabelLocaleID(nameof(AgoraSettings.Enabled)), "Enable Agora" },
                { _settings.GetOptionDescLocaleID(nameof(AgoraSettings.Enabled)),
                    "Runs the political layer. Turning this off leaves the city untouched and stops all Agora systems." },

                { _settings.GetOptionLabelLocaleID(nameof(AgoraSettings.LogDailyHeartbeat)), "Log daily heartbeat" },
                { _settings.GetOptionDescLocaleID(nameof(AgoraSettings.LogDailyHeartbeat)),
                    "Writes one line per in-game day to Player.log. Useful when verifying the mod is running; noisy otherwise." },
            };
        }

        public void Unload()
        {
        }
    }
}
